"""Game content: three defence cases with prosecution moves and law cards (French criminal law)."""

CASES = [
    {
        "id": "theft",
        "title": "The Forgotten Charger",
        "client": "Lea, 34, a nurse with no criminal record",
        "charge": "Theft",
        "law": "Art. 311-1 Code penal",
        "definition": "Theft is the fraudulent taking of something that belongs to someone else. 'Fraudulent' means you knew and wanted to take it.",
        "facts": [
            "Lea paid EUR 62 of groceries at the self-checkout.",
            "A EUR 19 phone charger was found in her handbag at the exit gate.",
            "CCTV shows her slipping it into her bag during a phone call.",
            "Her phone log: a 9-minute urgent call from her hospital at that moment.",
            "She immediately offered to pay for it.",
        ],
        "start": 35,
        "scenes": [
            "Friday evening. Lea, a nurse, pays at the self-checkout - on an urgent call from her hospital.",
            "CCTV: mid-call, a EUR 19 charger slips into her handbag.",
            "At the exit the guard stops her. She offers to pay at once. Charge: theft.",
        ],
        "takeaway": "Theft (art. 311-1) = taking + someone else's property + fraudulent INTENT. Without intent, there is no theft.",
        "keywords": ["intent", "intention", "forgot", "distract", "phone", "call", "hospital", "paid", "doubt", "innocen", "121-3", "good faith", "fraudulent"],
        "moves": [
            {"id": "m1", "title": "The CCTV footage", "text": "The video clearly shows her placing the charger in her own bag. What more do you need?", "law": "Art. 311-1 C. pen. - the taking", "power": 14},
            {"id": "m2", "title": "The security guard", "text": "Our guard says she 'looked nervous' and walked out fast.", "law": "Witness testimony", "power": 12},
            {"id": "m3", "title": "Concealment", "text": "Why the handbag and not the basket? Hiding an item shows she meant to steal it.", "law": "Art. 311-1 C. pen. - intent", "power": 14},
        ],
        "cards": [
            {"id": "t1", "name": "No intent, no offence", "kind": "Principle", "law": "Art. 121-3 C. pen.", "plain": "A crime or delit requires the intent to commit it. Forgetting is not stealing.", "power": 9, "counters": "m3",
             "lesson": "Theft needs a FRAUDULENT taking. If she did not mean to take it, the mental element is missing."},
            {"id": "t2", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "She is innocent until proven guilty. The prosecution must prove every element, including intent.", "power": 7, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "t3", "name": "Phone records", "kind": "Evidence", "law": "Art. 427 CPP - free evidence", "plain": "A 9-minute urgent call from the hospital, exactly when the charger went into the bag.", "power": 8, "counters": "m1",
             "lesson": "Context turns 'she hid it' into 'she was distracted'. Judges weigh all evidence freely (art. 427 CPP)."},
            {"id": "t4", "name": "Receipt and offer to pay", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "She paid EUR 62 and offered to pay the EUR 19 on the spot.", "power": 6, "counters": "",
             "lesson": "Behaviour consistent with good faith supports the absence of fraudulent intent."},
            {"id": "t5", "name": "Question the guard", "kind": "Witness", "law": "Art. 427 CPP", "plain": "'Looking nervous' is an impression, not a fact. What did he actually see?", "power": 6, "counters": "m2",
             "lesson": "Subjective impressions weigh little against objective facts."},
            {"id": "t6", "name": "Character witness", "kind": "Witness", "law": "Art. 132-1 C. pen.", "plain": "Her head nurse: 12 years of service, a spotless record.", "power": 3, "counters": "",
             "lesson": "Good character helps a little, but it mostly matters for the sentence (art. 132-1), not for guilt."},
            {"id": "t7", "name": "Self-defence", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "Argue that she acted in legitimate self-defence.", "power": -8, "counters": "",
             "lesson": "Self-defence requires an unjustified attack. Nobody attacked Lea, so the jury is confused."},
            {"id": "t8", "name": "Statute of limitations", "kind": "Argument", "law": "Art. 8 CPP", "plain": "Argue the case is too old to be prosecuted.", "power": -7, "counters": "",
             "lesson": "Delits are time-barred after 6 years. This happened last month, so the argument backfires."},
        ],
    },
    {
        "id": "trust",
        "title": "The Company Card",
        "client": "Marc, 41, regional sales manager",
        "charge": "Breach of trust",
        "law": "Art. 314-1 Code penal",
        "definition": "Breach of trust is misusing money or property that was handed to you for a specific purpose, to the detriment of its owner.",
        "facts": [
            "Marc's employer gave him a company card for business expenses.",
            "Over 3 months he spent EUR 3,200 on personal hotels and dinners.",
            "He says his director orally allowed 'advances' deducted from his bonus.",
            "An email from the director: 'Fine, we'll take it off your bonus - D.'",
            "Marc has already repaid EUR 1,600.",
        ],
        "start": 30,
        "scenes": [
            "Marc, a sales manager, puts EUR 3,200 of personal costs on his company card.",
            "The company accountant flags the expenses.",
            "Marc shows his director's email: 'Fine, we'll take it off your bonus.' Charge: breach of trust.",
        ],
        "takeaway": "Breach of trust (art. 314-1) = property handed over for a set purpose, then misused (detournement). An AGREED use is not a misuse. Unlike theft, there is no 'taking'.",
        "keywords": ["authoris", "authoriz", "agreed", "permission", "email", "director", "bonus", "deduct", "purpose", "detournement", "misappropriat", "314-1", "doubt", "consent"],
        "moves": [
            {"id": "m1", "title": "The bank statements", "text": "EUR 3,200 of personal spending on a company card. The numbers speak for themselves.", "law": "Art. 314-1 C. pen. - funds handed over", "power": 14},
            {"id": "m2", "title": "The expense policy", "text": "The written policy forbids ANY personal use of the card. He misused it, full stop.", "law": "Art. 314-1 C. pen. - misuse", "power": 13},
            {"id": "m3", "title": "The director denies", "text": "The director testifies he never authorised any advance.", "law": "Witness testimony", "power": 14},
        ],
        "cards": [
            {"id": "b1", "name": "Agreed use is not misuse", "kind": "Principle", "law": "Art. 314-1 C. pen.", "plain": "Breach of trust requires using funds against the agreed purpose. If the boss agreed, there is no misuse.", "power": 9, "counters": "m2",
             "lesson": "The key element is the 'detournement': a use contrary to what was agreed. A specific agreement overrides the general policy."},
            {"id": "b2", "name": "The director's email", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "'Fine, we'll take it off your bonus - D.'", "power": 10, "counters": "m3",
             "lesson": "Written evidence contradicts the director's denial in court."},
            {"id": "b3", "name": "The bonus practice", "kind": "Witness", "law": "Art. 427 CPP", "plain": "A colleague confirms that advances were routinely deducted from bonuses.", "power": 7, "counters": "m1",
             "lesson": "A known practice explains the transactions instead of just denying them."},
            {"id": "b4", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "The prosecution must prove the misuse. Doubt benefits Marc.", "power": 6, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "b5", "name": "It is not theft", "kind": "Argument", "law": "Art. 311-1 vs 314-1", "plain": "The card was handed over voluntarily. There was no 'taking'.", "power": 1, "counters": "",
             "lesson": "Correct law, but that is exactly WHY he is charged with breach of trust rather than theft. It barely helps."},
            {"id": "b6", "name": "He paid half back", "kind": "Argument", "law": "Art. 314-1 C. pen.", "plain": "He repaid EUR 1,600, so surely the matter is settled?", "power": -6, "counters": "",
             "lesson": "Repaying does NOT erase a breach of trust once committed (settled case law). It only helps at sentencing."},
            {"id": "b7", "name": "Defence of property", "kind": "Argument", "law": "Art. 122-5 al. 2 C. pen.", "plain": "He was protecting his own interests.", "power": -8, "counters": "",
             "lesson": "Defending property means stopping a crime against goods. That is irrelevant here."},
            {"id": "b8", "name": "State of necessity", "kind": "Argument", "law": "Art. 122-7 C. pen.", "plain": "He had no other choice.", "power": -5, "counters": "",
             "lesson": "Necessity requires a current or imminent danger. Hotels and dinners are not one."},
        ],
    },
    {
        "id": "defence",
        "title": "The Broken Bottle",
        "client": "Karim, 27, a bike courier",
        "charge": "Intentional violence (over 8 days' incapacity)",
        "law": "Art. 222-11 Code penal",
        "definition": "Deliberately hurting someone so badly they cannot work for over 8 days is a delit. But self-defence (art. 122-5) removes criminal liability.",
        "facts": [
            "In a bar, a man smashed a bottle and lunged at Karim with it.",
            "Karim threw a single punch. The man fell and broke his jaw (20 days' incapacity).",
            "They had argued 10 minutes earlier.",
            "The bar camera timestamps: 2 seconds between the lunge and the punch.",
            "The barman saw the whole scene.",
        ],
        "start": 30,
        "scenes": [
            "A Paris bar, late at night. Karim, a bike courier, argues with a stranger.",
            "Ten minutes later the man smashes a bottle and lunges. Karim throws one punch.",
            "The man's jaw is broken: 20 days' incapacity. Charge: intentional violence.",
        ],
        "takeaway": "Self-defence (art. 122-5) = an unjustified attack + an immediate, necessary and proportionate response.",
        "keywords": ["122-5", "self-defen", "legitimate defen", "proportion", "bottle", "immediate", "simultaneous", "necess", "attack", "unjustified", "seconds", "barman", "doubt"],
        "moves": [
            {"id": "m1", "title": "A broken jaw", "text": "20 days' incapacity. That is not defence, that is punishment.", "law": "Art. 222-11 C. pen.", "power": 14},
            {"id": "m2", "title": "He could have left", "text": "The exit was 5 metres away. He chose to fight.", "law": "Art. 122-5 C. pen. - necessity", "power": 12},
            {"id": "m3", "title": "An earlier argument", "text": "They argued 10 minutes before. This was revenge, not defence.", "law": "Art. 122-5 C. pen. - simultaneity", "power": 13},
        ],
        "cards": [
            {"id": "d1", "name": "Self-defence", "kind": "Principle", "law": "Art. 122-5 C. pen.", "plain": "No criminal liability for an immediate, necessary and proportionate response to an unjustified attack.", "power": 10, "counters": "",
             "lesson": "Self-defence has 4 conditions: an unjustified attack, plus an immediate, necessary and proportionate response."},
            {"id": "d2", "name": "Proportionality", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "One bare-handed punch against a broken bottle. Compare the means, not just the result.", "power": 9, "counters": "m1",
             "lesson": "Proportionality compares the means of defence with the threat, not only the injury caused."},
            {"id": "d3", "name": "Camera timeline", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "2 seconds between the lunge and the punch.", "power": 9, "counters": "m3",
             "lesson": "Simultaneity: the defence must happen 'at the same time' as the attack. Revenge later would not count, but this was immediate."},
            {"id": "d4", "name": "Imminent danger", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "A broken bottle 1 metre away leaves no time to reach the exit.", "power": 7, "counters": "m2",
             "lesson": "Necessity: in that instant there was no other safe option."},
            {"id": "d5", "name": "The barman", "kind": "Witness", "law": "Art. 427 CPP", "plain": "'The other guy went for him with the bottle.'", "power": 6, "counters": "",
             "lesson": "An independent witness confirms that the attack was unjustified."},
            {"id": "d6", "name": "Presumed self-defence", "kind": "Argument", "law": "Art. 122-6 C. pen.", "plain": "Claim the legal presumption of self-defence.", "power": -6, "counters": "",
             "lesson": "The art. 122-6 presumption only covers repelling a night-time break-in into a home, or violent thieves. A bar fight is not covered."},
            {"id": "d7", "name": "He was drunk", "kind": "Argument", "law": "Case law", "plain": "Karim had 4 beers. He was not himself.", "power": -7, "counters": "",
             "lesson": "Voluntary intoxication is not an excuse in French criminal law. It never removes liability."},
            {"id": "d8", "name": "He was insulted", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "The other man insulted him first.", "power": -4, "counters": "",
             "lesson": "Words alone do not justify violence. Self-defence needs a real attack, which is the bottle, not the insults."},
        ],
    },
]

# Reconstruction sound effects per shot ("a+b" = b starts a moment after a). Synthesised in Verdict.cs.
SFX = {"theft": ["store", "cctv", "alarm+siren"], "trust": ["store", "typing", "phone"], "defence": ["bar", "glass+punch", "siren"]}
for _c in CASES:
    _c.setdefault("look", _c["id"])
    _c["sfx"] = SFX[_c["id"]]
