"""Game content: six defence cases with prosecution moves and law cards (French criminal law)."""

CASES = [
    {
        "id": "theft",
        "title": "The Forgotten Charger",
        "client": "Lea, 34, a nurse with no criminal record",
        "charge": "Theft",
        "law": "Art. 311-1 Code penal",
        "definition": "Theft is the fraudulent taking of something that belongs to someone else. 'Fraudulent' means you knew and wanted to take it.",
        "facts": [
            "Lea paid EUR 62 of groceries at the self-checkout.",
            "A EUR 19 phone charger was found in her handbag at the exit gate.",
            "CCTV shows her slipping it into her bag during a phone call.",
            "Her phone log: a 9-minute urgent call from her hospital at that moment.",
            "She immediately offered to pay for it.",
        ],
        "start": 35,
        "scenes": [
            "Friday evening. Lea, a nurse, pays at the self-checkout - on an urgent call from her hospital.",
            "CCTV: mid-call, a EUR 19 charger slips into her handbag.",
            "At the exit the guard stops her. She offers to pay at once. Charge: theft.",
        ],
        "takeaway": "Theft (art. 311-1) = taking + someone else's property + fraudulent INTENT. Without intent, there is no theft.",
        "keywords": ["intent", "intention", "forgot", "distract", "phone", "call", "hospital", "paid", "doubt", "innocen", "121-3", "good faith", "fraudulent"],
        "moves": [
            {"id": "m1", "title": "The CCTV footage", "text": "The video clearly shows her placing the charger in her own bag. What more do you need?", "law": "Art. 311-1 C. pen. - the taking", "power": 14},
            {"id": "m2", "title": "The security guard", "text": "Our guard says she 'looked nervous' and walked out fast.", "law": "Witness testimony", "power": 12},
            {"id": "m3", "title": "Concealment", "text": "Why the handbag and not the basket? Hiding an item shows she meant to steal it.", "law": "Art. 311-1 C. pen. - intent", "power": 14},
        ],
        "cards": [
            {"id": "t1", "name": "No intent, no offence", "kind": "Principle", "law": "Art. 121-3 C. pen.", "plain": "A crime or delit requires the intent to commit it. Forgetting is not stealing.", "power": 9, "counters": "m3",
             "lesson": "Theft needs a FRAUDULENT taking. If she did not mean to take it, the mental element is missing."},
            {"id": "t2", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "She is innocent until proven guilty. The prosecution must prove every element, including intent.", "power": 7, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "t3", "name": "Phone records", "kind": "Evidence", "law": "Art. 427 CPP - free evidence", "plain": "A 9-minute urgent call from the hospital, exactly when the charger went into the bag.", "power": 8, "counters": "m1",
             "lesson": "Context turns 'she hid it' into 'she was distracted'. Judges weigh all evidence freely (art. 427 CPP)."},
            {"id": "t4", "name": "Receipt and offer to pay", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "She paid EUR 62 and offered to pay the EUR 19 on the spot.", "power": 6, "counters": "",
             "lesson": "Behaviour consistent with good faith supports the absence of fraudulent intent."},
            {"id": "t5", "name": "Question the guard", "kind": "Witness", "law": "Art. 427 CPP", "plain": "'Looking nervous' is an impression, not a fact. What did he actually see?", "power": 6, "counters": "m2",
             "lesson": "Subjective impressions weigh little against objective facts."},
            {"id": "t6", "name": "Character witness", "kind": "Witness", "law": "Art. 132-1 C. pen.", "plain": "Her head nurse: 12 years of service, a spotless record.", "power": 3, "counters": "",
             "lesson": "Good character helps a little, but it mostly matters for the sentence (art. 132-1), not for guilt."},
            {"id": "t7", "name": "Self-defence", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "Argue that she acted in legitimate self-defence.", "power": -8, "counters": "",
             "lesson": "Self-defence requires an unjustified attack. Nobody attacked Lea, so the jury is confused."},
            {"id": "t8", "name": "Statute of limitations", "kind": "Argument", "law": "Art. 8 CPP", "plain": "Argue the case is too old to be prosecuted.", "power": -7, "counters": "",
             "lesson": "Delits are time-barred after 6 years. This happened last month, so the argument backfires."},
        ],
    },
    {
        "id": "trust",
        "title": "The Company Card",
        "client": "Marc, 41, regional sales manager",
        "charge": "Breach of trust",
        "law": "Art. 314-1 Code penal",
        "definition": "Breach of trust is misusing money or property that was handed to you for a specific purpose, to the detriment of its owner.",
        "facts": [
            "Marc's employer gave him a company card for business expenses.",
            "Over 3 months he spent EUR 3,200 on personal hotels and dinners.",
            "He says his director orally allowed 'advances' deducted from his bonus.",
            "An email from the director: 'Fine, we'll take it off your bonus - D.'",
            "Marc has already repaid EUR 1,600.",
        ],
        "start": 30,
        "scenes": [
            "Marc, a sales manager, puts EUR 3,200 of personal costs on his company card.",
            "The company accountant flags the expenses.",
            "Marc shows his director's email: 'Fine, we'll take it off your bonus.' Charge: breach of trust.",
        ],
        "takeaway": "Breach of trust (art. 314-1) = property handed over for a set purpose, then misused (detournement). An AGREED use is not a misuse. Unlike theft, there is no 'taking'.",
        "keywords": ["authoris", "authoriz", "agreed", "permission", "email", "director", "bonus", "deduct", "purpose", "detournement", "misappropriat", "314-1", "doubt", "consent"],
        "moves": [
            {"id": "m1", "title": "The bank statements", "text": "EUR 3,200 of personal spending on a company card. The numbers speak for themselves.", "law": "Art. 314-1 C. pen. - funds handed over", "power": 14},
            {"id": "m2", "title": "The expense policy", "text": "The written policy forbids ANY personal use of the card. He misused it, full stop.", "law": "Art. 314-1 C. pen. - misuse", "power": 13},
            {"id": "m3", "title": "The director denies", "text": "The director testifies he never authorised any advance.", "law": "Witness testimony", "power": 14},
        ],
        "cards": [
            {"id": "b1", "name": "Agreed use is not misuse", "kind": "Principle", "law": "Art. 314-1 C. pen.", "plain": "Breach of trust requires using funds against the agreed purpose. If the boss agreed, there is no misuse.", "power": 9, "counters": "m2",
             "lesson": "The key element is the 'detournement': a use contrary to what was agreed. A specific agreement overrides the general policy."},
            {"id": "b2", "name": "The director's email", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "'Fine, we'll take it off your bonus - D.'", "power": 10, "counters": "m3",
             "lesson": "Written evidence contradicts the director's denial in court."},
            {"id": "b3", "name": "The bonus practice", "kind": "Witness", "law": "Art. 427 CPP", "plain": "A colleague confirms that advances were routinely deducted from bonuses.", "power": 7, "counters": "m1",
             "lesson": "A known practice explains the transactions instead of just denying them."},
            {"id": "b4", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "The prosecution must prove the misuse. Doubt benefits Marc.", "power": 6, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "b5", "name": "It is not theft", "kind": "Argument", "law": "Art. 311-1 vs 314-1", "plain": "The card was handed over voluntarily. There was no 'taking'.", "power": 1, "counters": "",
             "lesson": "Correct law, but that is exactly WHY he is charged with breach of trust rather than theft. It barely helps."},
            {"id": "b6", "name": "He paid half back", "kind": "Argument", "law": "Art. 314-1 C. pen.", "plain": "He repaid EUR 1,600, so surely the matter is settled?", "power": -6, "counters": "",
             "lesson": "Repaying does NOT erase a breach of trust once committed (settled case law). It only helps at sentencing."},
            {"id": "b7", "name": "Defence of property", "kind": "Argument", "law": "Art. 122-5 al. 2 C. pen.", "plain": "He was protecting his own interests.", "power": -8, "counters": "",
             "lesson": "Defending property means stopping a crime against goods. That is irrelevant here."},
            {"id": "b8", "name": "State of necessity", "kind": "Argument", "law": "Art. 122-7 C. pen.", "plain": "He had no other choice.", "power": -5, "counters": "",
             "lesson": "Necessity requires a current or imminent danger. Hotels and dinners are not one."},
        ],
    },
    {
        "id": "defence",
        "title": "The Broken Bottle",
        "client": "Karim, 27, a bike courier",
        "charge": "Intentional violence (over 8 days' incapacity)",
        "law": "Art. 222-11 Code penal",
        "definition": "Deliberately hurting someone so badly they cannot work for over 8 days is a delit. But self-defence (art. 122-5) removes criminal liability.",
        "facts": [
            "In a bar, a man smashed a bottle and lunged at Karim with it.",
            "Karim threw a single punch. The man fell and broke his jaw (20 days' incapacity).",
            "They had argued 10 minutes earlier.",
            "The bar camera timestamps: 2 seconds between the lunge and the punch.",
            "The barman saw the whole scene.",
        ],
        "start": 30,
        "scenes": [
            "A Paris bar, late at night. Karim, a bike courier, argues with a stranger.",
            "Ten minutes later the man smashes a bottle and lunges. Karim throws one punch.",
            "The man's jaw is broken: 20 days' incapacity. Charge: intentional violence.",
        ],
        "takeaway": "Self-defence (art. 122-5) = an unjustified attack + an immediate, necessary and proportionate response.",
        "keywords": ["122-5", "self-defen", "legitimate defen", "proportion", "bottle", "immediate", "simultaneous", "necess", "attack", "unjustified", "seconds", "barman", "doubt"],
        "moves": [
            {"id": "m1", "title": "A broken jaw", "text": "20 days' incapacity. That is not defence, that is punishment.", "law": "Art. 222-11 C. pen.", "power": 14},
            {"id": "m2", "title": "He could have left", "text": "The exit was 5 metres away. He chose to fight.", "law": "Art. 122-5 C. pen. - necessity", "power": 12},
            {"id": "m3", "title": "An earlier argument", "text": "They argued 10 minutes before. This was revenge, not defence.", "law": "Art. 122-5 C. pen. - simultaneity", "power": 13},
        ],
        "cards": [
            {"id": "d1", "name": "Self-defence", "kind": "Principle", "law": "Art. 122-5 C. pen.", "plain": "No criminal liability for an immediate, necessary and proportionate response to an unjustified attack.", "power": 10, "counters": "",
             "lesson": "Self-defence has 4 conditions: an unjustified attack, plus an immediate, necessary and proportionate response."},
            {"id": "d2", "name": "Proportionality", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "One bare-handed punch against a broken bottle. Compare the means, not just the result.", "power": 9, "counters": "m1",
             "lesson": "Proportionality compares the means of defence with the threat, not only the injury caused."},
            {"id": "d3", "name": "Camera timeline", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "2 seconds between the lunge and the punch.", "power": 9, "counters": "m3",
             "lesson": "Simultaneity: the defence must happen 'at the same time' as the attack. Revenge later would not count, but this was immediate."},
            {"id": "d4", "name": "Imminent danger", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "A broken bottle 1 metre away leaves no time to reach the exit.", "power": 7, "counters": "m2",
             "lesson": "Necessity: in that instant there was no other safe option."},
            {"id": "d5", "name": "The barman", "kind": "Witness", "law": "Art. 427 CPP", "plain": "'The other guy went for him with the bottle.'", "power": 6, "counters": "",
             "lesson": "An independent witness confirms that the attack was unjustified."},
            {"id": "d6", "name": "Presumed self-defence", "kind": "Argument", "law": "Art. 122-6 C. pen.", "plain": "Claim the legal presumption of self-defence.", "power": -6, "counters": "",
             "lesson": "The art. 122-6 presumption only covers repelling a night-time break-in into a home, or violent thieves. A bar fight is not covered."},
            {"id": "d7", "name": "He was drunk", "kind": "Argument", "law": "Case law", "plain": "Karim had 4 beers. He was not himself.", "power": -7, "counters": "",
             "lesson": "Voluntary intoxication is not an excuse in French criminal law. It never removes liability."},
            {"id": "d8", "name": "He was insulted", "kind": "Argument", "law": "Art. 122-5 C. pen.", "plain": "The other man insulted him first.", "power": -4, "counters": "",
             "lesson": "Words alone do not justify violence. Self-defence needs a real attack, which is the bottle, not the insults."},
        ],
    },
    {
        "id": "fraud",
        "title": "The Resold Tickets",
        "client": "Thomas, 38, a delivery driver",
        "charge": "Fraud (escroquerie)",
        "law": "Art. 313-1 Code penal",
        "definition": "Fraud is getting someone to hand over money by deceiving them with a false name, a false capacity or 'fraudulent manoeuvres'. A plain lie is usually not enough, and the deceit must be intentional.",
        "facts": [
            "Thomas sold two concert tickets online for EUR 300, under his real name.",
            "At the stadium gate the buyers' tickets were rejected as duplicates.",
            "A week earlier Thomas had bought them from an online reseller for EUR 280.",
            "His bank statement shows the EUR 280 payment to that reseller.",
            "The listing carried the site's automatic 'verified seller' badge.",
        ],
        "start": 35,
        "scenes": [
            "Thomas, a delivery driver, posts two concert tickets online for EUR 300, under his own name.",
            "Concert night: the buyers' tickets are rejected at the gate. Duplicates.",
            "Thomas shows the police his own receipt from a reseller. Charge: fraud.",
        ],
        "takeaway": "Fraud (art. 313-1) = deceit (false name, false capacity or fraudulent manoeuvres) + money handed over + INTENT to deceive. A seller who was himself deceived is not a fraudster.",
        "keywords": ["intent", "good faith", "deceived", "himself", "reseller", "receipt", "real name", "manoeuvre", "313-1", "doubt", "knew", "121-3", "victim"],
        "moves": [
            {"id": "m1", "title": "Worthless tickets", "text": "He sold two worthless tickets and pocketed EUR 300. The victims lost everything.", "law": "Art. 313-1 C. pen. - money handed over", "power": 14},
            {"id": "m2", "title": "A professional ad", "text": "Polished photos and a 'verified seller' badge. Classic fraudulent manoeuvres.", "law": "Art. 313-1 C. pen. - manoeuvres", "power": 13},
            {"id": "m3", "title": "He must have known", "text": "He bought from a stranger online. Anyone would have known they were fakes.", "law": "Art. 313-1 C. pen. - intent", "power": 13},
        ],
        "cards": [
            {"id": "f1", "name": "Deceived, not deceiver", "kind": "Principle", "law": "Art. 121-3 C. pen.", "plain": "Fraud requires the intent to deceive. Thomas believed the tickets were real - he paid EUR 280 for them himself.", "power": 9, "counters": "m3",
             "lesson": "Fraud is an intentional offence: the prosecution must prove he KNEW the tickets were fake. Someone who was scammed and resells in good faith lacks the mental element."},
            {"id": "f2", "name": "The reseller receipt", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "Bank statement: EUR 280 paid to the reseller a week before the sale.", "power": 8, "counters": "m1",
             "lesson": "Objective evidence shows he lost money too. A EUR 20 margin hardly fits a planned scam."},
            {"id": "f3", "name": "The platform's badge", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "'Verified seller' is added automatically by the site to any ID-checked account. He did not create it.", "power": 7, "counters": "m2",
             "lesson": "Fraudulent manoeuvres must come from the accused. A label added by the platform is not his manoeuvre."},
            {"id": "f4", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "The prosecution must prove he knew. Doubt benefits Thomas.", "power": 6, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "f5", "name": "Real name, real account", "kind": "Argument", "law": "Art. 313-1 C. pen.", "plain": "He sold under his own name and bank account - hardly how a fraudster hides.", "power": 5, "counters": "",
             "lesson": "A false name is one way to commit fraud. Selling under his real identity points to good faith."},
            {"id": "f6", "name": "He refunded half", "kind": "Argument", "law": "Art. 313-1 C. pen.", "plain": "He paid EUR 150 back, so the matter is settled.", "power": -6, "counters": "",
             "lesson": "Refunding does not erase a fraud once committed. It may help at sentencing, but the question is whether he deceived anyone."},
            {"id": "f7", "name": "It was just a lie", "kind": "Argument", "law": "Case law - simple lie", "plain": "Every seller exaggerates. A lie alone is not fraud.", "power": -4, "counters": "",
             "lesson": "A plain lie alone is usually not fraud - but arguing he lied admits he knew! The defence is that he did NOT know."},
            {"id": "f8", "name": "State of necessity", "kind": "Argument", "law": "Art. 122-7 C. pen.", "plain": "He needed the money for his rent.", "power": -7, "counters": "",
             "lesson": "Necessity requires a current or imminent danger. Needing money never justifies deceiving buyers."},
        ],
    },
    {
        "id": "recel",
        "title": "The Bargain Phone",
        "client": "Ines, 22, an engineering student",
        "charge": "Receiving stolen goods (recel)",
        "law": "Art. 321-1 Code penal",
        "definition": "Recel is holding or passing on something you KNOW comes from a crime or delit. The receiver does not need to be the thief, but knowledge of the origin must be proven.",
        "facts": [
            "Ines bought a smartphone for EUR 250 from a stranger in a metro station.",
            "The same model sells for about EUR 600 second-hand.",
            "Two weeks later police traced it by its IMEI: it had been stolen in a street robbery.",
            "The seller's ad said 'Moving abroad Friday, quick sale' and he gave her a printed invoice, later found to be forged.",
            "She used the phone openly, with a SIM card registered in her own name.",
        ],
        "start": 35,
        "scenes": [
            "A metro station, 9 p.m. Ines, a student, buys a phone from a stranger for EUR 250.",
            "Two weeks later police knock at her door: the phone was stolen in a robbery.",
            "Ines shows them the invoice the seller gave her. Charge: receiving stolen goods.",
        ],
        "takeaway": "Recel (art. 321-1) = holding a thing that comes from a crime or delit + KNOWING its origin. Price and circumstances can be used to prove knowledge, so the defence must explain them.",
        "keywords": ["know", "knew", "knowledge", "invoice", "good faith", "price", "intent", "origin", "321-1", "doubt", "own name", "sim", "openly", "121-3", "ad"],
        "moves": [
            {"id": "m1", "title": "Too cheap to be honest", "text": "EUR 250 for a EUR 600 phone. Anyone would have understood it was stolen.", "law": "Art. 321-1 C. pen. - knowledge", "power": 14},
            {"id": "m2", "title": "A metro handover", "text": "Cash, a stranger, a metro corridor at night. These are the codes of stolen goods.", "law": "Art. 321-1 C. pen. - circumstances", "power": 13},
            {"id": "m3", "title": "She held it", "text": "The phone from the robbery was in her hands for two weeks. That is possession.", "law": "Art. 321-1 C. pen. - holding", "power": 12},
        ],
        "cards": [
            {"id": "r1", "name": "No knowledge, no recel", "kind": "Principle", "law": "Art. 321-1 / 121-3 C. pen.", "plain": "Recel requires knowing the thing was stolen. Holding it is not enough.", "power": 9, "counters": "m3",
             "lesson": "Possession is only the material element. Without proof she KNEW the origin, the mental element of recel is missing."},
            {"id": "r2", "name": "The forged invoice", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "She asked for an invoice and got one. Even the police needed checks to spot the forgery.", "power": 8, "counters": "m2",
             "lesson": "Asking for and receiving an invoice is what a careful buyer does. It supports her good faith despite the setting."},
            {"id": "r3", "name": "The 'quick sale' ad", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "'Moving abroad Friday, quick sale.' A plausible reason for a low price.", "power": 8, "counters": "m1",
             "lesson": "A low price is a clue, not proof. A credible explanation for it weakens the inference that she knew."},
            {"id": "r4", "name": "Used openly", "kind": "Argument", "law": "Art. 427 CPP", "plain": "She put in a SIM registered in her own name - fully traceable.", "power": 6, "counters": "",
             "lesson": "Someone who knows a phone is stolen usually hides it. Open, traceable use points to good faith."},
            {"id": "r5", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "The prosecution must prove she knew. Doubt benefits Ines.", "power": 6, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "r6", "name": "She did not steal it", "kind": "Argument", "law": "Art. 311-1 vs 321-1", "plain": "She was nowhere near the robbery.", "power": 1, "counters": "",
             "lesson": "True but beside the point: recel punishes the receiver, who need not be the thief. That is exactly why the charge is recel, not theft."},
            {"id": "r7", "name": "She will give it back", "kind": "Argument", "law": "Art. 321-1 C. pen.", "plain": "She is ready to return the phone, so no harm done.", "power": -5, "counters": "",
             "lesson": "Returning the item does not erase recel if she knew. It only matters for the sentence."},
            {"id": "r8", "name": "Error of law", "kind": "Argument", "law": "Art. 122-3 C. pen.", "plain": "She did not know buying a phone in the metro was illegal.", "power": -7, "counters": "",
             "lesson": "Art. 122-3 covers an unavoidable mistake about the LAW. Buying second-hand is legal; the question is whether she knew the phone was stolen - a question of fact."},
        ],
    },
    {
        "id": "damage",
        "title": "The Painted Shutter",
        "client": "Hugo, 19, an art student",
        "charge": "Damage to property",
        "law": "Art. 322-1 Code penal",
        "definition": "Deliberately destroying or damaging someone else's property is a delit. Graffiti causing only slight damage is a lesser offence, and painting with the permission of the person in charge is not a damage.",
        "facts": [
            "At 2 a.m. Hugo painted a large mural on a shop's closed metal shutter.",
            "The owner says cleaning will cost EUR 1,800 and files a complaint.",
            "Hugo has a text from the shop manager, the owner's daughter: 'Go ahead, paint the shutter.'",
            "The shop is open all day; it was raining and 4 degrees that night.",
            "An expert says the paint can be removed without harming the shutter.",
        ],
        "start": 30,
        "scenes": [
            "2 a.m. Hugo, an art student, spray-paints a mural on a closed shop shutter.",
            "A street camera films him, hood up, spray can in hand.",
            "Morning: the owner calls the police. Hugo shows a text: 'Go ahead, paint it.' Charge: damage to property.",
        ],
        "takeaway": "Damage to property (art. 322-1) = damaging SOMEONE ELSE's property + intent. Permission from the person in charge removes the intent; slight graffiti damage is a lesser offence (art. 322-1 al. 2).",
        "keywords": ["consent", "permission", "authoris", "authoriz", "text", "manager", "daughter", "good faith", "intent", "slight", "removable", "322-1", "doubt", "hood", "rain"],
        "moves": [
            {"id": "m1", "title": "Caught on camera", "text": "The street camera shows him spraying the shutter at 2 a.m. The act is proven.", "law": "Art. 322-1 C. pen. - the damage", "power": 14},
            {"id": "m2", "title": "The hood", "text": "Hood up, in the middle of the night: he was hiding his face. That is an aggravating circumstance.", "law": "Art. 322-3 C. pen. - face concealment", "power": 12},
            {"id": "m3", "title": "Nobody allowed it", "text": "The owner is formal: he never authorised anything on his property.", "law": "Art. 322-1 C. pen. - another's property", "power": 13},
        ],
        "cards": [
            {"id": "p1", "name": "The manager's text", "kind": "Evidence", "law": "Art. 427 CPP", "plain": "'Go ahead, paint the shutter' - from the manager who runs the shop every day.", "power": 9, "counters": "m3",
             "lesson": "Permission from the person running the shop shows Hugo believed, in good faith, that the work was allowed."},
            {"id": "p2", "name": "No intent to damage", "kind": "Principle", "law": "Art. 121-3 C. pen.", "plain": "Hugo thought he had permission. Damage to property must be deliberate.", "power": 8, "counters": "m1",
             "lesson": "The camera proves the act, not the intent. Art. 322-1 needs a deliberate damage to someone else's property against their will."},
            {"id": "p3", "name": "A hood is not a mask", "kind": "Argument", "law": "Art. 322-3 C. pen.", "plain": "It was raining and 4 degrees. He painted at night because the shop is open all day.", "power": 7, "counters": "m2",
             "lesson": "Face concealment (art. 322-3) means hiding your face to avoid being identified. A hood in the rain is not that."},
            {"id": "p4", "name": "Removable paint", "kind": "Evidence", "law": "Expert report - Art. 427 CPP", "plain": "An expert confirms the paint washes off without harming the shutter.", "power": 5, "counters": "",
             "lesson": "If the property is not really damaged, the material element is weak - at most slight damage (art. 322-1 al. 2)."},
            {"id": "p5", "name": "Presumption of innocence", "kind": "Principle", "law": "Art. 9 DDHC - Art. prelim. CPP", "plain": "The prosecution must prove every element, including intent. Doubt benefits Hugo.", "power": 6, "counters": "",
             "lesson": "The burden of proof is on the prosecution, and any doubt benefits the accused."},
            {"id": "p6", "name": "Freedom of expression", "kind": "Argument", "law": "Art. 10 ECHR", "plain": "It is art! Artistic freedom protects him.", "power": -6, "counters": "",
             "lesson": "Freedom of expression does not allow using someone else's property without consent. Courts reject this defence for unauthorised graffiti."},
            {"id": "p7", "name": "He will clean it", "kind": "Argument", "law": "Art. 322-1 C. pen.", "plain": "He offers to clean the shutter himself.", "power": -4, "counters": "",
             "lesson": "Repairing afterwards does not erase the offence. It can help with the sentence, not with guilt."},
            {"id": "p8", "name": "State of necessity", "kind": "Argument", "law": "Art. 122-7 C. pen.", "plain": "Artists need walls to show their work.", "power": -7, "counters": "",
             "lesson": "Necessity requires a current or imminent danger. Wanting a canvas is not a danger."},
        ],
    },
]

# Reconstruction sound effects per shot ("a+b" = b starts a moment after a). Synthesised in Verdict.cs.
SFX = {"theft": ["store", "cctv", "alarm+siren"], "trust": ["store", "typing", "phone"], "defence": ["bar", "glass+punch", "siren"],
       "fraud": ["typing", "crowd+alarm", "phone"], "recel": ["train", "door+siren", "typing"], "damage": ["spray", "cctv", "siren"]}
for _c in CASES:
    _c.setdefault("look", _c["id"])
    _c["sfx"] = SFX[_c["id"]]

# Extra accusations for the human prosecutor in multiplayer. Neutralised by any helpful card of the given kind.
PROSECUTION_EXTRA = [
    {"id": "g1", "title": "Think of the victim", "text": "Members of the jury, someone was harmed here. Someone has to answer for it.",
     "law": "Appeal to emotion", "power": 9, "kind": "Principle",
     "lesson": "A legal principle answers an emotional appeal: the jury must decide on the facts and the law, not on sympathy (art. 427 CPP)."},
    {"id": "g2", "title": "Doubt the defence", "text": "Everything the defence offers comes from the accused and their friends. Why believe a word of it?",
     "law": "Credibility attack", "power": 8, "kind": "Evidence",
     "lesson": "Objective evidence answers an attack on credibility: records and documents do not depend on who presents them."},
]
